// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrN_Gkd6k-xlq5ob28uJ0IFwP4NQPbnD4',
    appId: '1:1015772279436:web:4f57c44bbdb69db9d041a9',
    messagingSenderId: '1015772279436',
    projectId: 'lumispace-c51b5',
    authDomain: 'lumispace-c51b5.firebaseapp.com',
    databaseURL: 'https://lumispace-c51b5-default-rtdb.firebaseio.com',
    storageBucket: 'lumispace-c51b5.firebasestorage.app',
    measurementId: 'G-B90QGKWFJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHTz_LV1cpvyybBWHj337HfGQ2Hwk8K0k',
    appId: '1:1015772279436:android:9ed56980230374bad041a9',
    messagingSenderId: '1015772279436',
    projectId: 'lumispace-c51b5',
    databaseURL: 'https://lumispace-c51b5-default-rtdb.firebaseio.com',
    storageBucket: 'lumispace-c51b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAndfalXIVkIXwgNC2o7D2cgstwM8Kz6gA',
    appId: '1:1015772279436:ios:843730a6c00d88ddd041a9',
    messagingSenderId: '1015772279436',
    projectId: 'lumispace-c51b5',
    databaseURL: 'https://lumispace-c51b5-default-rtdb.firebaseio.com',
    storageBucket: 'lumispace-c51b5.firebasestorage.app',
    iosBundleId: 'com.example.lumispace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAndfalXIVkIXwgNC2o7D2cgstwM8Kz6gA',
    appId: '1:1015772279436:ios:843730a6c00d88ddd041a9',
    messagingSenderId: '1015772279436',
    projectId: 'lumispace-c51b5',
    databaseURL: 'https://lumispace-c51b5-default-rtdb.firebaseio.com',
    storageBucket: 'lumispace-c51b5.firebasestorage.app',
    iosBundleId: 'com.example.lumispace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrN_Gkd6k-xlq5ob28uJ0IFwP4NQPbnD4',
    appId: '1:1015772279436:web:343d97eba335141ad041a9',
    messagingSenderId: '1015772279436',
    projectId: 'lumispace-c51b5',
    authDomain: 'lumispace-c51b5.firebaseapp.com',
    databaseURL: 'https://lumispace-c51b5-default-rtdb.firebaseio.com',
    storageBucket: 'lumispace-c51b5.firebasestorage.app',
    measurementId: 'G-ZXS3HW3ZE1',
  );
}
